---
name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions: {}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: szksh-lab-2/test-local-action@pr-2
        with:
          is: "true"
